required: sudo

services:
  - docker

language: go

go:
  - 1.9

before_install:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck

  # install gnatsd & nats-streaming
  - wget https://github.com/nats-io/nats-streaming-server/releases/download/v0.5.0/nats-streaming-server-v0.5.0-linux-amd64.zip
  - unzip -d gnatsd -j nats-streaming-server-v0.5.0-linux-amd64.zip
  - ./gnatsd/nats-streaming-server &

  # give the queues some time to start.
  - sleep 5

before_script:
  - go vet ./...
  - golint ./...
  - megacheck ./...

script:
    - make testMGO
    - make testPublishers


